# -*- coding: utf-8 -*-
"""Geolocation_data_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhr6NX72RIR6B81zNJ29AONNP_xUVnFl
"""

# IMPORT
import pandas as pd
import numpy as np
import os

"""#Charger et visualiser les données"""

fname = "ts007aageby5yearagebandslowerlayersuperoutputareas.csv"

def load_table(path: str) -> pd.DataFrame:
    ext = os.path.splitext(path)[1].lower()

    if ext in [".csv"]:
        return pd.read_csv(path)
    if ext in [".tsv"]:
        return pd.read_csv(path, sep="\t")
    if ext in [".txt"]:

        df = pd.read_csv(path, sep="\t", engine="python")
        if df.shape[1] == 1:
            df = pd.read_csv(path, sep=r"\s+", engine="python")
        return df
    if ext in [".parquet"]:
        return pd.read_parquet(path)
    if ext in [".xlsx", ".xls"]:
        return pd.read_excel(path)


    try:
        return pd.read_csv(path)
    except Exception:
        return pd.read_csv(path, sep="\t", engine="python")

df = load_table(fname)
print("Shape:", df.shape)
print("Columns:", list(df.columns))
df.head(10)

"""Lower Layer Super Output Areas Code

Identifiant officiel ONS d’une Lower Layer Super Output Area (LSOA).
Ce code est unique et stable dans le temps et permet d’identifier de manière non ambiguë chaque LSOA en Angleterre et au Pays de Galles.

Lower Layer Super Output Areas Label

Libellé textuel de la Lower Layer Super Output Area correspondant au code LSOA.
Il s’agit d’un nom lisible par un humain, destiné à l’interprétation et à l’affichage.

Age (B) (18 categories) Code

Code numérique représentant une tranche d’âge définie par l’ONS.
Chaque valeur correspond à une catégorie d’âge parmi 18 tranches quinquennales standardisées.

Age (B) (18 categories) Label

Libellé textuel associé à la tranche d’âge codée.
Il décrit explicitement l’intervalle d’âge (par exemple : Aged 20 to 24 years).

Count

Effectif de population correspondant à la combinaison (LSOA, tranche d’âge).
Il représente le nombre de résidents recensés dans cette tranche d’âge au sein de la LSOA considérée.
"""

fname = "Output_Area_to_Lower_layer_Super_Output_Area_to_Middle_layer_Super_Output_Area_to_Local_Authority_District_(December_2021)_Lookup_in_England_and_Wales_v3.csv"

def load_table(path: str) -> pd.DataFrame:
    ext = os.path.splitext(path)[1].lower()

    if ext in [".csv"]:
        return pd.read_csv(path)
    if ext in [".tsv"]:
        return pd.read_csv(path, sep="\t")
    if ext in [".txt"]:

        df = pd.read_csv(path, sep="\t", engine="python")
        if df.shape[1] == 1:
            df = pd.read_csv(path, sep=r"\s+", engine="python")
        return df
    if ext in [".parquet"]:
        return pd.read_parquet(path)
    if ext in [".xlsx", ".xls"]:
        return pd.read_excel(path)


    try:
        return pd.read_csv(path)
    except Exception:
        return pd.read_csv(path, sep="\t", engine="python")

df = load_table(fname)
print("Shape:", df.shape)
print("Columns:", list(df.columns))
df.head(10)

"""OA21CD

Identifiant officiel ONS d’une Output Area (OA) selon la géographie 2021.
Ce code identifie l’unité géographique statistique la plus fine utilisée dans le recensement.

LSOA21CD

Identifiant officiel ONS de la Lower Layer Super Output Area (LSOA) associée à l’Output Area.
Il permet de regrouper plusieurs OA au sein d’une même LSOA (géographie 2021).

LSOA21NM

Libellé textuel de la Lower Layer Super Output Area (LSOA) en anglais.
Il s’agit du nom lisible correspondant au code LSOA21CD.

LSOA21NMW

Libellé textuel de la Lower Layer Super Output Area (LSOA) en gallois.
Cette colonne peut contenir des valeurs manquantes lorsque la traduction galloise n’est pas applicable.

MSOA21CD

Identifiant officiel ONS de la Middle Layer Super Output Area (MSOA) associée à la LSOA.
Il permet de relier les LSOA à un niveau géographique intermédiaire plus agrégé (géographie 2021).

MSOA21NM

Libellé textuel de la Middle Layer Super Output Area (MSOA) en anglais.
Il correspond au nom lisible de la MSOA associée.

MSOA21NMW

Libellé textuel de la Middle Layer Super Output Area (MSOA) en gallois.
Cette colonne peut contenir des valeurs manquantes lorsque la traduction galloise n’est pas fournie.

LAD22CD

Identifiant officiel ONS du Local Authority District (LAD) selon la géographie 2022.
Il permet de rattacher les unités statistiques à une autorité administrative locale.

LAD22NM

Libellé textuel du Local Authority District (LAD) en anglais.
Il correspond au nom officiel de l’autorité locale.

LAD22NMW

Libellé textuel du Local Authority District (LAD) en gallois.
Cette colonne peut contenir des valeurs manquantes lorsque la traduction galloise n’est pas disponible.

ObjectId

Identifiant technique interne du jeu de données.
Il sert uniquement à l’indexation ou au suivi des enregistrements et n’a pas de signification géographique ou statistique.

"""

fname = "15595611502713788.csv"

df = pd.read_csv(
    fname,
    skiprows=5,
    engine="python"
)

print("Shape:", df.shape)
print("Columns:", list(df.columns))
df.head(10)

"""Total

Effectif total de la population âgée de 20 ans et plus au sein de l’unité géographique considérée (Output Area 2021).
Cette valeur correspond à la somme des effectifs de toutes les tranches d’âge détaillées dans les colonnes Aged 20 to 24 years jusqu’à Aged 85 years and over.

mnemonic

Identifiant mnémotechnique de l’unité géographique de recensement.
Dans ce jeu de données, il correspond au code officiel de l’Output Area 2021 et est identique à la valeur de la colonne 2021 output area.
"""

fname = "802075638742233.csv"

df = pd.read_csv(
    fname,
    skiprows=5,
    engine="python"
)

print("Shape:", df.shape)
print("Columns:", list(df.columns))
df.head(10)

"""Total: All households

Nombre total de ménages (households) recensés dans l’unité géographique considérée (Output Area 2021).
Cette valeur représente l’effectif total des ménages, toutes tailles confondues, et sert de base de calcul pour les pourcentages associés aux différentes catégories de taille de ménage.

Ce jeu de données présente la répartition des ménages au niveau du Local Authority District (LAD) selon le type de ménage d’une personne et la tranche d’âge des résidents, pour l’année de référence 2021. Chaque ligne correspond à une combinaison entre un district local (identifié par son code et son nom), une catégorie de ménage d’une personne (par exemple one-person household aged 66 years and over ou one-person household: other), une tranche d’âge standardisée (de aged 15 years and under à aged 50 years and over), et un effectif associé indiquant le nombre de ménages correspondant à cette combinaison. Le jeu inclut également des modalités spécifiques telles que does not apply, utilisées pour coder des cas particuliers ou non applicables dans la classification statistique.
"""

import pandas as pd

fname = "RM057-2021-1-filtered-2026-01-29T14_02_13Z.csv"

df = pd.read_csv(fname, engine="python")

print("Shape:", df.shape)
print("Columns:", list(df.columns))
df.head(10)

df = df.rename(columns={
    "Lower tier local authorities Code": "lad_code",
    "Lower tier local authorities": "lad_name",
    "Household composition (15 categories) Code": "hh_comp_code",
    "Household composition (15 categories)": "hh_comp",
    "Age (4 categories) Code": "age_code",
    "Age (4 categories)": "age",
    "Observation": "obs"
})

print(df.columns)

df_rutland = df[df["lad_code"] == "E06000017"].copy()

print("Rutland shape:", df_rutland.shape)
df_rutland["lad_name"].unique()

adult_bins = {"Aged 21 to 29 years", "Aged 30 years and over"}

df_rutland_20p = df_rutland[df_rutland["age"].isin(adult_bins)].copy()

print("Rutland 20+ shape:", df_rutland_20p.shape)
df_rutland_20p["age"].value_counts()

output_fname = "RM057_Rutland_adults_20plus.csv"

df_rutland_20p.to_csv(
    output_fname,
    index=False
)

print(f"Saved file: {output_fname}")

hh_size_map = {
    # One-person households
    "One-person household: Aged 66 years and over": 1,
    "One-person household: Other": 1,

    # Single family households (older only)
    "Single family household: All aged 66 years and over": 2,

    # Couples (minimum certain d'adultes)
    "Single family household: Married or civil partnership couple: No children": 2,
    "Single family household: Married or civil partnership couple: Dependent children": 2,
    "Single family household: Married or civil partnership couple: All children non-dependent": "3+",

    "Single family household: Cohabiting couple family: No children": 2,
    "Single family household: Cohabiting couple family: With dependent children": 2,
    "Single family household: Cohabiting couple family: All children non-dependent": "3+",

    # Lone parent
    "Single family household: Lone parent family: With dependent children": 1,
    "Single family household: Lone parent family: All children non-dependent": "3+",

    # Other / complex households
    "Other household types: Other related household: Other family composition": "3+",
    "Other household types: With dependent children": "3+",
    "Other household types: Other, including all full-time students and all aged 66 years and over": "3+",
}


df_rutland_20p["household_size"] = df_rutland_20p["hh_comp"].map(hh_size_map)


df_rutland_20p = df_rutland_20p[df_rutland_20p["household_size"].notna()].copy()


df_rutland_20p["household_size"].value_counts()

dist_hh = (
    df_rutland_20p
    .groupby("household_size", as_index=False)["obs"]
    .sum()
    .rename(columns={"obs": "adult_count"})
)


total_adults = dist_hh["adult_count"].sum()


dist_hh["proportion"] = dist_hh["adult_count"] / total_adults

dist_hh, total_adults

assert abs(dist_hh["proportion"].sum() - 1.0) < 1e-6


(
    df_rutland_20p
    .groupby(["household_size", "hh_comp"], as_index=False)["obs"]
    .sum()
    .sort_values(["household_size", "obs"], ascending=[True, False])
)

dist_fname = "Rutland_household_size_distribution_adults_20plus.csv"
dist_hh.to_csv(dist_fname, index=False)

print(f"Saved: {dist_fname}")

"""# MSOA"""

import pandas as pd

fname_msoa = "RM057-2021-1-filtered-2026-01-29T14_53_39Z.csv"
df_msoa = pd.read_csv(fname_msoa, engine="python")

print("MSOA shape:", df_msoa.shape)
print("Columns:", list(df_msoa.columns))
df_msoa.head()

fname_lookup = "Output_Area_to_Lower_layer_Super_Output_Area_to_Middle_layer_Super_Output_Area_to_Local_Authority_District_(December_2021)_Lookup_in_England_and_Wales_v3.csv"

df_lookup = pd.read_csv(fname_lookup, engine="python")

print("Lookup shape:", df_lookup.shape)
print("Lookup columns:", list(df_lookup.columns))
df_lookup.head()

LAD_CODE_RUTLAND = "E06000017"

msoa_rutland = (
    df_lookup[df_lookup["LAD22CD"] == LAD_CODE_RUTLAND]["MSOA21CD"]
    .dropna()
    .unique()
)

print("Number of MSOA in Rutland:", len(msoa_rutland))
msoa_rutland

df_msoa_rutland = df_msoa[df_msoa["Middle layer Super Output Areas Code"].isin(msoa_rutland)].copy()

print("Rutland MSOA shape:", df_msoa_rutland.shape)
df_msoa_rutland.head()

df_msoa = df_msoa.rename(columns={
    "Middle layer Super Output Areas Code": "msoa_code",
    "Middle layer Super Output Areas": "msoa_name",
    "Household composition (15 categories) Code": "hh_comp_code",
    "Household composition (15 categories)": "hh_comp",
    "Age (4 categories) Code": "age_code",
    "Age (4 categories)": "age",
    "Observation": "obs",
})

df_lookup = df_lookup.rename(columns={
    "MSOA21CD": "msoa_code",
    "LAD22CD": "lad_code",
})

LAD_CODE_RUTLAND = "E06000017"

msoa_rutland = (
    df_lookup[df_lookup["lad_code"] == LAD_CODE_RUTLAND]["msoa_code"]
    .dropna()
    .unique()
)

print("Rutland MSOAs:", len(msoa_rutland))
msoa_rutland

df_msoa_rutland = df_msoa[df_msoa["msoa_code"].isin(msoa_rutland)].copy()

print("Rutland MSOA shape:", df_msoa_rutland.shape)
df_msoa_rutland.head()

df_check = df_msoa_rutland.merge(
    df_lookup[["msoa_code", "lad_code"]].drop_duplicates(),
    on="msoa_code",
    how="left"
)

df_check["lad_code"].unique()

adult_bins = {"Aged 21 to 29 years", "Aged 30 years and over"}
df_msoa_rutland_20p = df_msoa_rutland[df_msoa_rutland["age"].isin(adult_bins)].copy()

print("Rutland MSOA 20+ shape:", df_msoa_rutland_20p.shape)
df_msoa_rutland_20p["age"].value_counts()

hh_size_map = {
    "One-person household: Aged 66 years and over": 1,
    "One-person household: Other": 1,

    "Single family household: All aged 66 years and over": 2,

    "Single family household: Married or civil partnership couple: No children": 2,
    "Single family household: Married or civil partnership couple: Dependent children": 2,
    "Single family household: Married or civil partnership couple: All children non-dependent": "3+",

    "Single family household: Cohabiting couple family: No children": 2,
    "Single family household: Cohabiting couple family: With dependent children": 2,
    "Single family household: Cohabiting couple family: All children non-dependent": "3+",

    "Single family household: Lone parent family: With dependent children": 1,
    "Single family household: Lone parent family: All children non-dependent": "3+",

    "Other household types: Other related household: Other family composition": "3+",
    "Other household types: With dependent children": "3+",
    "Other household types: Other, including all full-time students and all aged 66 years and over": "3+",
}

df_msoa_rutland_20p["household_size"] = df_msoa_rutland_20p["hh_comp"].map(hh_size_map)


df_msoa_rutland_20p = df_msoa_rutland_20p[df_msoa_rutland_20p["household_size"].notna()].copy()

df_msoa_rutland_20p["household_size"].value_counts()

msoa_counts = (
    df_msoa_rutland_20p
    .groupby(["msoa_code", "msoa_name", "household_size"], as_index=False)["obs"]
    .sum()
    .rename(columns={"obs": "adult_count"})
)


msoa_totals = (
    msoa_counts
    .groupby(["msoa_code", "msoa_name"], as_index=False)["adult_count"]
    .sum()
    .rename(columns={"adult_count": "adult_total"})
)


msoa_dist = msoa_counts.merge(msoa_totals, on=["msoa_code", "msoa_name"], how="left")
msoa_dist["p"] = msoa_dist["adult_count"] / msoa_dist["adult_total"]

msoa_dist.sort_values(["msoa_code", "household_size"]).head(20)

pivot = (
    msoa_dist
    .pivot_table(index=["msoa_code", "msoa_name"],
                 columns="household_size",
                 values="p",
                 fill_value=0.0)
    .reset_index()
)


if 1 not in pivot.columns: pivot[1] = 0.0
if 2 not in pivot.columns: pivot[2] = 0.0
if "3+" not in pivot.columns: pivot["3+"] = 0.0

pivot = pivot.rename(columns={1: "p_hh1", 2: "p_hh2", "3+": "p_hh3plus"})


s = pivot["p_hh1"] + pivot["p_hh2"] + pivot["p_hh3plus"]
pivot["p_hh1"] /= s
pivot["p_hh2"] /= s
pivot["p_hh3plus"] /= s


pivot = pivot.merge(msoa_totals, on=["msoa_code", "msoa_name"], how="left")

pivot

out_fname = "Rutland_MSOA_household_size_dist_adults20plus.csv"
pivot.to_csv(out_fname, index=False)
print("Saved:", out_fname)

"""# OA Household size"""

import pandas as pd

speakers_fname = "OA_speakers_E06000017.xlsx"
df_spk = pd.read_excel(speakers_fname)

print("Speakers shape:", df_spk.shape)
print("Columns:", list(df_spk.columns))
df_spk.head()

import pandas as pd

fname_gender = "28858161698474894.csv"

df_gender = pd.read_csv(
    fname_gender,
    skiprows=6,
    engine="python"
)

print("Shape:", df_gender.shape)
print("Columns:", list(df_gender.columns))
df_gender.head()

lookup_fname = "Output_Area_to_Lower_layer_Super_Output_Area_to_Middle_layer_Super_Output_Area_to_Local_Authority_District_(December_2021)_Lookup_in_England_and_Wales_v3.csv"

df_lookup = pd.read_csv(lookup_fname, engine="python")

print("Lookup columns:", list(df_lookup.columns))
df_lookup.head()

df_lookup = df_lookup.rename(columns={
    "OA21CD": "oa_code",
    "LAD22CD": "lad_code"
})

df_gender = df_gender.rename(columns={
    "2021 output area": "oa_code",
    "All persons": "all_persons_pct",
    "Female": "female_pct",
    "Male": "male_pct",
})

LAD_CODE_RUTLAND = "E06000017"

oa_rutland = (
    df_lookup[df_lookup["lad_code"] == LAD_CODE_RUTLAND]["oa_code"]
    .dropna()
    .unique()
)

print("Number of OA in Rutland:", len(oa_rutland))

df_gender_rutland = df_gender[df_gender["oa_code"].isin(oa_rutland)].copy()

print("Rutland OA gender shape:", df_gender_rutland.shape)
df_gender_rutland.head()

df_check = df_gender_rutland.merge(
    df_lookup[["oa_code", "lad_code"]].drop_duplicates(),
    on="oa_code",
    how="left"
)

df_check["lad_code"].unique()

out_fname = "OA_gender_E06000017.csv"
df_gender_rutland.to_csv(out_fname, index=False)

print("Saved:", out_fname)

"""# Attribution"""

import pandas as pd


df_spk_gender = pd.read_csv(
    "spk2gender_enroll",
    sep=r"\s+",
    names=["speaker_id", "gender"],
    engine="python"
)

df_spk_gender["gender"].value_counts()

df_gender_rutland.head()

import pandas as pd
import numpy as np


df_oa = pd.read_excel("OA_speakers_E06000017.xlsx").copy()


df_oa = df_oa.rename(columns={
    "OA_code": "oa_code",
    "assigned_speakers": "n_speakers",
    "LSOA21CD": "lsoa_code",
    "MSOA21CD": "msoa_code",
    "LAD22CD": "lad_code",
})


df_oa["oa_code"] = df_oa["oa_code"].astype(str).str.strip()
df_oa["n_speakers"] = pd.to_numeric(df_oa["n_speakers"], errors="coerce").fillna(0).astype(int)

print(df_oa.head())
print("Total speakers expected:", df_oa["n_speakers"].sum())

df_spk_gender = pd.read_csv(
    "spk2gender_enroll",
    sep=r"\s+",
    names=["speaker_id", "gender"],
    engine="python"
)

df_spk_gender["speaker_id"] = df_spk_gender["speaker_id"].astype(str).str.strip()
df_spk_gender["gender"] = df_spk_gender["gender"].astype(str).str.strip().str.lower()

print(df_spk_gender["gender"].value_counts())
print("Total speakers:", len(df_spk_gender))

df_gender_rutland["oa_code"] = df_gender_rutland["oa_code"].astype(str).str.strip()

df_oa = df_oa.merge(
    df_gender_rutland[["oa_code", "female_pct", "male_pct"]],
    on="oa_code",
    how="left"
)

print("Missing gender rows:", df_oa["female_pct"].isna().sum())
df_oa.head()

df_oa["n_f"] = np.rint(df_oa["n_speakers"] * df_oa["female_pct"] / 100.0).astype(int)
df_oa["n_m"] = df_oa["n_speakers"] - df_oa["n_f"]


assert (df_oa["n_f"] >= 0).all()
assert (df_oa["n_m"] >= 0).all()
assert (df_oa["n_f"] + df_oa["n_m"] == df_oa["n_speakers"]).all()

df_oa[["oa_code","n_speakers","female_pct","male_pct","n_f","n_m"]].head()

import numpy as np

available_f = (df_spk_gender["gender"] == "f").sum()
available_m = (df_spk_gender["gender"] == "m").sum()


df_oa["target_f_cont"] = df_oa["n_speakers"] * (df_oa["female_pct"] / 100.0)


target_sum = df_oa["target_f_cont"].sum()
scale = available_f / target_sum
df_oa["target_f_scaled"] = df_oa["target_f_cont"] * scale


df_oa["n_f"] = np.floor(df_oa["target_f_scaled"]).astype(int)

df_oa["n_f"] = df_oa["n_f"].clip(lower=0, upper=df_oa["n_speakers"])


current_f = int(df_oa["n_f"].sum())
remaining = int(available_f - current_f)

df_oa["frac"] = df_oa["target_f_scaled"] - np.floor(df_oa["target_f_scaled"])

print("available_f:", available_f, "current_f:", current_f, "remaining:", remaining)

if remaining > 0:

    candidates = df_oa[df_oa["n_f"] < df_oa["n_speakers"]].sort_values("frac", ascending=False).index
    for idx in candidates[:remaining]:
        df_oa.at[idx, "n_f"] += 1
elif remaining < 0:

    candidates = df_oa[df_oa["n_f"] > 0].sort_values("frac", ascending=True).index
    for idx in candidates[:(-remaining)]:
        df_oa.at[idx, "n_f"] -= 1


df_oa["n_m"] = df_oa["n_speakers"] - df_oa["n_f"]


assert int(df_oa["n_f"].sum()) == int(available_f)
assert int(df_oa["n_m"].sum()) == int(available_m)
assert (df_oa["n_f"] >= 0).all() and (df_oa["n_f"] <= df_oa["n_speakers"]).all()
assert (df_oa["n_f"] + df_oa["n_m"] == df_oa["n_speakers"]).all()


df_oa.drop(columns=["frac"], inplace=True)

df_oa[["oa_code","n_speakers","female_pct","target_f_cont","target_f_scaled","n_f","n_m"]].head()

df_f = df_spk_gender[df_spk_gender["gender"] == "f"].sample(frac=1, random_state=42).reset_index(drop=True)
df_m = df_spk_gender[df_spk_gender["gender"] == "m"].sample(frac=1, random_state=42).reset_index(drop=True)

f_cursor = 0
m_cursor = 0
parts = []

for _, row in df_oa.iterrows():
    oa = row["oa_code"]
    nf = int(row["n_f"])
    nm = int(row["n_m"])

    chunk_f = df_f.iloc[f_cursor:f_cursor+nf].copy()
    chunk_f["oa_code"] = oa
    f_cursor += nf

    chunk_m = df_m.iloc[m_cursor:m_cursor+nm].copy()
    chunk_m["oa_code"] = oa
    m_cursor += nm

    parts.append(chunk_f)
    parts.append(chunk_m)

df_spk_assigned = pd.concat(parts, ignore_index=True)

print("Assigned:", df_spk_assigned.shape)
print(df_spk_assigned["gender"].value_counts())
df_spk_assigned.head()

oa_counts = df_spk_assigned.groupby("oa_code").size().reset_index(name="count")
check = df_oa[["oa_code","n_speakers"]].merge(oa_counts, on="oa_code", how="left").fillna(0)
check["count"] = check["count"].astype(int)
print("OA exact:", (check["count"] == check["n_speakers"]).all())


print("Total F assigned:", (df_spk_assigned["gender"]=="f").sum())
print("Total M assigned:", (df_spk_assigned["gender"]=="m").sum())

df_export = df_spk_assigned.merge(
    df_oa[["oa_code", "lsoa_code", "msoa_code", "lad_code"]],
    on="oa_code",
    how="left"
)


print("Rows:", df_export.shape[0])
print("Missing LSOA:", df_export["lsoa_code"].isna().sum())
print("Missing MSOA:", df_export["msoa_code"].isna().sum())
print("Missing LAD :", df_export["lad_code"].isna().sum())
print("Unique LADs:", df_export["lad_code"].dropna().unique())


out_csv = "Rutland_speakers_assigned_OA_LSOA_MSOA_LAD_gender.csv"
df_export.to_csv(out_csv, index=False)
print("Saved:", out_csv)

import pandas as pd
import numpy as np

dist_fname = "Rutland_MSOA_household_size_dist_adults20plus.csv"
df_dist = pd.read_csv(dist_fname)


print("df_dist columns:", list(df_dist.columns))
df_dist.head()

df_work = df_export.merge(
    df_dist[["msoa_code", "p_hh1", "p_hh2", "p_hh3plus"]],
    on="msoa_code",
    how="left"
)

print("Missing MSOA dist rows:", df_work[["p_hh1","p_hh2","p_hh3plus"]].isna().any(axis=1).sum())
df_work.head()

rng = np.random.default_rng(42)

probs = df_work[["p_hh1","p_hh2","p_hh3plus"]].to_numpy(dtype=float)
probs = probs / probs.sum(axis=1, keepdims=True)

choices = np.array(["1", "2", "3+"])
df_work["household_size"] = choices[
    [rng.choice(3, p=p) for p in probs]
]

df_work["household_size"].value_counts()

def build_households_within_oa_mf_pairs(df_oa: pd.DataFrame, rng: np.random.Generator):
    oa = str(df_oa["oa_code"].iloc[0])


    df_oa = df_oa.sample(frac=1.0, random_state=int(rng.integers(0, 1e9))).copy()

    rows = []
    hh_counter = 0

    def new_hh_id():
        nonlocal hh_counter
        hh_counter += 1
        return f"{oa}_HH{hh_counter:06d}"


    df1 = df_oa[df_oa["household_size"] == "1"]
    for spk in df1["speaker_id"].tolist():
        hh_id = new_hh_id()
        rows.append((spk, hh_id, "1", None))


    df2 = df_oa[df_oa["household_size"] == "2"]
    f2 = df2[df2["gender"] == "f"]["speaker_id"].tolist()
    m2 = df2[df2["gender"] == "m"]["speaker_id"].tolist()

    n_mixed = min(len(f2), len(m2))
    for i in range(n_mixed):
        hh_id = new_hh_id()
        rows.append((f2[i], hh_id, "2", True))
        rows.append((m2[i], hh_id, "2", True))


    leftover = f2[n_mixed:] + m2[n_mixed:]


    pool = df_oa[df_oa["household_size"] == "3+"]["speaker_id"].tolist() + leftover

    i = 0
    while i < len(pool):
        rem = len(pool) - i
        if rem >= 3:
            take = 3 if rem != 4 else
            hh_id = new_hh_id()
            for spk in pool[i:i+take]:
                rows.append((spk, hh_id, "3+", None))
            i += take
        else:

            if rem == 2:
                hh_id = new_hh_id()
                rows.append((pool[i], hh_id, "2_fallback", False))
                rows.append((pool[i+1], hh_id, "2_fallback", False))
            else:
                hh_id = new_hh_id()
                rows.append((pool[i], hh_id, "1_fallback", False))
            break

    out = pd.DataFrame(rows, columns=["speaker_id", "household_id", "hh_size_final", "is_mf_couple"])
    return df_oa.merge(out, on="speaker_id", how="left")

rng = np.random.default_rng(123)

df_final = (
    df_work.groupby("oa_code", group_keys=False)
    .apply(lambda g: build_households_within_oa_mf_pairs(g, rng))
)

print("Missing household_id:", df_final["household_id"].isna().sum())
df_final.head()

couples = df_final[df_final["hh_size_final"] == "2"].copy()

hh_couple = couples.groupby("household_id").agg(
    n=("speaker_id","count"),
    n_f=("gender", lambda s: (s=="f").sum()),
    n_m=("gender", lambda s: (s=="m").sum()),
).reset_index()

hh_couple["is_mf"] = (hh_couple["n"]==2) & (hh_couple["n_f"]==1) & (hh_couple["n_m"]==1)

print("Couples total:", len(hh_couple))
print("MF couples  :", hh_couple["is_mf"].sum())
print("MF rate     :", hh_couple["is_mf"].mean())

out_csv = "Rutland_speakers_with_households_OA_LSOA_MSOA_LAD.csv"
df_final.to_csv(out_csv, index=False)
print("Saved:", out_csv)

df_final["hh_size_final"].value_counts()

(
    df_final[df_final["hh_size_final"] == "2_fallback"]
    .groupby("oa_code")
    .size()
    .describe()
)